# CObj stuff
.set COBJ_GXPRI, 8
.set TEXT_GXPRI, 80
.set TEXT_GXLINK, 12

.set UNPRESSED_OPACITY, 0x5f
.set PRESSED_OPACITY, 0xff

# named regs
.set REG_DATA_ADDR, 29
.set REG_TEXT_STRUCT, 28
.set REG_CANVAS, 27
.set REG_COBJ, 26
.set REG_GOBJ, 25
.set REG_PLAYER_INDEX, 24
.set REG_BG_GOBJ, 23
.set REG_BG_JOBJ, 22
.set REG_SCRATCH, 12

## memory locations
# pointers to objs that are updated in callback
.set CONTROLLER_VISUAL_ADDR, 0x8046b790
.set CONTROLLER_VISUAL_OFFSET, 36

.set CV_MAIN_STICK_OFFSET, 0
.set CV_C_STICK_OFFSET, 4
.set CV_A_BTN_OFFSET, 8
.set CV_B_BTN_OFFSET, 12
.set CV_X_BTN_OFFSET, 16
.set CV_Y_BTN_OFFSET, 20
.set CV_L_BTN_OFFSET, 24
.set CV_R_BTN_OFFSET, 28
.set CV_Z_BTN_OFFSET, 32

# player static block
.set STATIC_BLOCK_ADDRESS, 0x80453080
.set STATIC_BLOCK_OFFSET, 0xe90
.set STATIC_BLOCK_PLAYER_TYPE_OFFSET, 0x0a

.set PLAYER_TYPE_NONE, 0x3

# player data
.set STATIC_ENTITY_ADDRESS, 0x80453130
.set STATIC_ENTITY_OFFSET, 0xe90
.set STATIC_ENTITY_DATA_POINTER_OFFSET, 0x2c

.set PD_MAIN_STICK_X_OFFSET, 0x620
.set PD_MAIN_STICK_Y_OFFSET, 0x624
.set PD_C_STICK_X_OFFSET, 0x638
.set PD_C_STICK_Y_OFFSET, 0x63C
.set PD_BTN_STATE_OFFSET, 0x65c

.set BTN_STATE_A_BIT, 0x100
.set BTN_STATE_B_BIT, 0x200
.set BTN_STATE_X_BIT, 0x400
.set BTN_STATE_Y_BIT, 0x800
.set BTN_STATE_Z_BIT, 0x10
.set BTN_STATE_R_BIT, 0x20
.set BTN_STATE_L_BIT, 0x40

# text struct
.set TEXT_STRUCT_X_OFFSET, 0x0
.set TEXT_STRUCT_Y_OFFSET, 0x4
.set TEXT_STRUCT_Z_OFFSET, 0x8
.set TEXT_STRUCT_WIDTH_OFFSET, 0x24
.set TEXT_STRUCT_HEIGHT_OFFSET, 0x28
.set TEXT_STRUCT_OPACITY_BYTE_OFFSET, 0x8f
