name: Build Check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:  
  ubuntu64:
    name: "Build Check"
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build"
        if: success()
        working-directory: ${{ github.workspace }}
        run: |
          sudo docker run --volume=${PWD}:/work --workdir=/work nikhilnarayana/devkitpro-slippi:latest make ini list
      - uses: numtide/clean-git-action@v1
